[2024-10-20T19:48:32.542+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-20T19:48:32.566+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: binance_data_extraction.run_binance_script scheduled__2024-10-19T00:00:00+00:00 [queued]>
[2024-10-20T19:48:32.576+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: binance_data_extraction.run_binance_script scheduled__2024-10-19T00:00:00+00:00 [queued]>
[2024-10-20T19:48:32.577+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-20T19:48:32.599+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_binance_script> on 2024-10-19 00:00:00+00:00
[2024-10-20T19:48:32.613+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=72) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-20T19:48:32.614+0000] {standard_task_runner.py:72} INFO - Started process 75 to run task
[2024-10-20T19:48:32.615+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'binance_data_extraction', 'run_binance_script', 'scheduled__2024-10-19T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/binance_data_extraction.py', '--cfg-path', '/tmp/tmpktbyj_35']
[2024-10-20T19:48:32.616+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask run_binance_script
[2024-10-20T19:48:32.689+0000] {task_command.py:467} INFO - Running <TaskInstance: binance_data_extraction.run_binance_script scheduled__2024-10-19T00:00:00+00:00 [running]> on host 3c6d286072f5
[2024-10-20T19:48:32.852+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='binance_data_extraction' AIRFLOW_CTX_TASK_ID='run_binance_script' AIRFLOW_CTX_EXECUTION_DATE='2024-10-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-19T00:00:00+00:00'
[2024-10-20T19:48:32.854+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-20T19:48:32.854+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-20T19:48:32.855+0000] {logging_mixin.py:190} INFO - Current task name:run_binance_script state:running start_date:2024-10-20 19:48:32.566545+00:00
[2024-10-20T19:48:32.855+0000] {logging_mixin.py:190} INFO - Dag name:binance_data_extraction and current dag run status:running
[2024-10-20T19:48:32.856+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-20T19:48:32.859+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/binance_data_extraction.py", line 18, in run_binance_script
    result = subprocess.run(
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/imakina/itba/integrador/venv/bin/python'
[2024-10-20T19:48:32.878+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-20T19:48:32.879+0000] {logging_mixin.py:190} INFO - Task start:2024-10-20 19:48:32.566545+00:00 end:2024-10-20 19:48:32.878101+00:00 duration:0.311556
[2024-10-20T19:48:32.879+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): run_binance_script> dag:<DAG: binance_data_extraction> dagrun:<DagRun binance_data_extraction @ 2024-10-19 00:00:00+00:00: scheduled__2024-10-19T00:00:00+00:00, state:running, queued_at: 2024-10-20 19:48:28.289132+00:00. externally triggered: False>
[2024-10-20T19:48:32.880+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: '/home/imakina/itba/integrador/venv/bin/python'
[2024-10-20T19:48:32.880+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=binance_data_extraction, task_id=run_binance_script, run_id=scheduled__2024-10-19T00:00:00+00:00, execution_date=20241019T000000, start_date=20241020T194832, end_date=20241020T194832
[2024-10-20T19:48:32.899+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-20T19:48:32.900+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 5 for task run_binance_script ([Errno 2] No such file or directory: '/home/imakina/itba/integrador/venv/bin/python'; 75)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/binance_data_extraction.py", line 18, in run_binance_script
    result = subprocess.run(
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/imakina/itba/integrador/venv/bin/python'
[2024-10-20T19:48:32.951+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-20T19:48:32.983+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-20T19:48:32.984+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-20T22:00:11.425+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-20T22:00:11.442+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: binance_data_extraction.run_binance_script scheduled__2024-10-19T00:00:00+00:00 [queued]>
[2024-10-20T22:00:11.450+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: binance_data_extraction.run_binance_script scheduled__2024-10-19T00:00:00+00:00 [queued]>
[2024-10-20T22:00:11.450+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-20T22:00:11.464+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_binance_script> on 2024-10-19 00:00:00+00:00
[2024-10-20T22:00:11.475+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=103) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-20T22:00:11.477+0000] {standard_task_runner.py:72} INFO - Started process 105 to run task
[2024-10-20T22:00:11.478+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'binance_data_extraction', 'run_binance_script', 'scheduled__2024-10-19T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/binance_data_extraction.py', '--cfg-path', '/tmp/tmplo86iryy']
[2024-10-20T22:00:11.479+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask run_binance_script
[2024-10-20T22:00:11.527+0000] {task_command.py:467} INFO - Running <TaskInstance: binance_data_extraction.run_binance_script scheduled__2024-10-19T00:00:00+00:00 [running]> on host a067a1017c42
[2024-10-20T22:00:11.600+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='binance_data_extraction' AIRFLOW_CTX_TASK_ID='run_binance_script' AIRFLOW_CTX_EXECUTION_DATE='2024-10-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-19T00:00:00+00:00'
[2024-10-20T22:00:11.601+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-20T22:00:11.602+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-20T22:00:11.602+0000] {logging_mixin.py:190} INFO - Current task name:run_binance_script state:running start_date:2024-10-20 22:00:11.443005+00:00
[2024-10-20T22:00:11.602+0000] {logging_mixin.py:190} INFO - Dag name:binance_data_extraction and current dag run status:running
[2024-10-20T22:00:11.602+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-20T22:00:11.642+0000] {logging_mixin.py:190} INFO - stdout: 
[2024-10-20T22:00:11.643+0000] {logging_mixin.py:190} INFO - stderr: python: can't open file '/opt/***/binance_prices.py': [Errno 2] No such file or directory
[2024-10-20T22:00:11.644+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-20T22:00:11.662+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-20T22:00:11.663+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=binance_data_extraction, task_id=run_binance_script, run_id=scheduled__2024-10-19T00:00:00+00:00, execution_date=20241019T000000, start_date=20241020T220011, end_date=20241020T220011
[2024-10-20T22:00:11.679+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-10-20T22:00:11.680+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-10-20T22:00:11.680+0000] {logging_mixin.py:190} INFO - Dag name:binance_data_extraction queued_at:2024-10-20 22:00:07.678113+00:00
[2024-10-20T22:00:11.681+0000] {logging_mixin.py:190} INFO - Task hostname:a067a1017c42 operator:PythonOperator
[2024-10-20T22:00:11.731+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-20T22:00:11.781+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-20T22:00:11.786+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
